home-assistant: error out if enabled component test does not exist
Unfortunately enabling xdist hides the error away and the tests fail
abruptly with no clear indication of what went wrong.

Only after disabling xdist (`-n auto`, `--dist loadfile`) you would see

> ERROR: file or directory not found: tests/components/openhome

https://github.com/NixOS/nixpkgs/pull/118453#issuecomment-814491608